
CREATE DATABASE Бібліотека CHARSET UTF8;
USE Бібліотека;

CREATE TABLE book(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
назва VARCHAR(120) NOT NULL,
опис TEXT,
ціна DECIMAL (5,2) NOT NULL,
isbn VARCHAR(20) NOT NULL UNIQUE,
Category_id INT NOT NULL
);

CREATE TABLE Category(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
назва VARCHAR(120) NOT NULL
);

CREATE TABLE author(
імя VARCHAR(50) NOT NULL,
прізвище VARCHAR(50) NOT NULL,
електронна_пошта VARCHAR(50) NOT NULL UNIQUE,
адресa VARCHAR(120) NOT NULL UNIQUE,
дата_народження DATE NOT NULL,
book_id INT NOT NULL
);

ALTER TABLE book ADD FOREIGN KEY (Category_id)
REFERENCES Category(id);




ALTER TABLE author ADD FOREIGN KEY (book_id)
REFERENCES book(id);



